-- WARNING: Generated by CoPilot 14/04/2026
-- This script identifies duplicate parameters in SQL Server Agent job steps for jobs that begin with 'DatabaseBackup%'.

SET NOCOUNT ON;

;WITH JobSteps AS
(
    SELECT
        j.name AS JobName,
        s.step_name,
        REPLACE(REPLACE(s.command, CHAR(13), ' '), CHAR(10), ' ') AS command
    FROM msdb.dbo.sysjobs j
    JOIN msdb.dbo.sysjobsteps s
        ON j.job_id = s.job_id
    WHERE j.name LIKE N'DatabaseBackup%'
      AND s.command LIKE '%@%'
),
SplitParams AS
(
    SELECT
        js.JobName,
        js.step_name,
        LTRIM(RTRIM(value)) AS Fragment
    FROM JobSteps js
    CROSS APPLY string_split(js.command, ',')
),
ExtractedParams AS
(
    SELECT
        JobName,
        step_name,
        ParameterName =
            LEFT(
                Fragment,
                CHARINDEX('=', Fragment + '=') - 1
            )
    FROM SplitParams
    WHERE Fragment LIKE '%@%=%'
),
NormalizedParams AS
(
    SELECT
        JobName,
        step_name,
        ParameterName =
            LTRIM(RTRIM(
                SUBSTRING(ParameterName,
                          PATINDEX('%@%', ParameterName),
                          200)
            ))
    FROM ExtractedParams
),
DuplicateParams AS
(
    SELECT
        JobName,
        step_name,
        ParameterName,
        COUNT(*) AS Occurrences
    FROM NormalizedParams
    GROUP BY JobName, step_name, ParameterName
    HAVING COUNT(*) > 1
)
SELECT
    JobName,
    step_name  AS JobStepName,
    ParameterName AS DuplicateParameter,
    Occurrences
FROM DuplicateParams
ORDER BY JobName, step_name, ParameterName;