SELECT TOP (1000) [RowID]
      ,[DatabaseName]
      ,[SchemaName]
      ,[TableName]
      ,[IndexName]
      ,[StartDate]
      ,[EndDate]
      ,[Success]
  FROM [test_index_optimisation].[dbo].[dsl_index_optimisation]
